apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: ns1
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ns1
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo-svc"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo-nkjs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongo
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "nkjs"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        - name: MONGO_INITDB_DATABASE
          value: "weather-app"
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-pv-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 0.5Gi
