apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-test
  namespace: ns1
  labels:
    app: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30005